### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by rschio** [nikolaydubina/go-graph-layout#9]
When testing the library I got this error:
```
layout/brandeskopf.go:191:9: no new variables on left side of :=
```
I would make a PR just removing the ':' but I think it's not that simple.

**Comment by rschio** [comment]
Or maybe it is... I removed the ':' and it's building, but when I tried to run the tests I got a panic.
I didn't dive deeper in the code...

**Comment by nikolaydubina** [comment]
we are moving this project to new owner. please give us some time.

if you see errors in new releases, check older ones

**Comment by rschio** [comment]
OK, thank you!

**Comment by gverger** [comment]
Hello @rschio the main branch is now fixed

**Comment by rschio** [comment]
Thank you!
